version: '3.9'
services:
  web:
    image: ruby
    container_name: web
    working_dir: /app
    volumes:
      - .:/app
      - ./gems:/usr/local/bundle
    command: bash -c "bundle && ruby server.rb"
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./database:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis

  sidekiq:
    image: ruby
    container_name: sidekiq
    working_dir: /app
    volumes:
      - .:/app
      - ./gems:/usr/local/bundle
    environment:
      REDIS_URL: redis://redis:6379/0
    command: bash -c "sidekiq -r ./helpers/import.rb"
    depends_on:
      - redis
