#!/bin/bash

docker network create rebase-labs-network

docker run \
  -d \
  --rm \
  --name postgresdb \
  --network rebase-labs-network \
  -e POSTGRES_USER=admin \
  -e POSTGRES_PASSWORD=admin \
  -v $(pwd)/database:/var/lib/postgresql/data \
  postgres

docker run \
  --rm \
  --name rebase-labs \
  --network rebase-labs-network \
  -w /app \
  -v $(pwd):/app \
  -v $(pwd)/gems:/usr/local/bundle \
  -p 3000:3000 \
  ruby \
  bash -c "bundle && ruby server.rb"
